auto: false
server: false
lsi: true
markdown: rdiscount
pygments: true
permalink: /:year/:month/:day/:title/
category_dir: category
tag_dir: tag
cloud_files:
  enabled: true
  datacentre: uk
  container: static.stut.net
  cname: http://static.stut.net/
  #upload_prefix:
  force_upload: false
